package repository

import (
	"database/sql"
	"backend/models"
)

type UserRepository interface {
	GetAllUsers() ([]models.User, error)
	GetUserByID(id string) (*models.User, error)
	GetUserByEmail(email string) (*models.User, error)
	CreateUser(user *models.User) error
	UpdateUser(id string, email string, password string) error
	DeleteUser(id string) error
}

type userRepository struct {
	db *sql.DB
}

func NewUserRepository(db *sql.DB) UserRepository {
	return &userRepository{db: db}
}

// Fetch all users from database
func (r *userRepository) GetAllUsers() ([]models.User, error) {
	query := `SELECT id, email FROM users`
	rows, err := r.db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []models.User
	for rows.Next() {
		var u models.User
		if err := rows.Scan(&u.ID, &u.Email); err != nil {
			return nil, err
		}
		users = append(users, u)
	}

	return users, nil
}

// Fetch a single user by ID
func (r *userRepository) GetUserByID(id string) (*models.User, error) {
	query := `SELECT id, email FROM users WHERE id = $1`
	row := r.db.QueryRow(query, id)

	var u models.User
	if err := row.Scan(&u.ID, &u.Email); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}

	return &u, nil
}

// Fetch a single user by email, including the password hash for login checks
func (r *userRepository) GetUserByEmail(email string) (*models.User, error) {
	query := `SELECT id, email, password FROM users WHERE email = $1`
	row := r.db.QueryRow(query, email)

	var u models.User
	if err := row.Scan(&u.ID, &u.Email, &u.Password); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}

	return &u, nil
}

// Insert a new user into the database; the id is generated by the database (SERIAL)
func (r *userRepository) CreateUser(user *models.User) error {
	query := `INSERT INTO users (email, password) VALUES ($1, $2) RETURNING id`
	return r.db.QueryRow(query, user.Email, user.Password).Scan(&user.ID)
}

// Update an existing user's email, and optionally their password
func (r *userRepository) UpdateUser(id string, email string, password string) error {
	var query string
	var args []interface{}

	if password != "" {
		query = `UPDATE users SET email = $1, password = $2 WHERE id = $3`
		args = []interface{}{email, password, id}
	} else {
		query = `UPDATE users SET email = $1 WHERE id = $2`
		args = []interface{}{email, id}
	}

	res, err := r.db.Exec(query, args...)
	if err != nil {
		return err
	}
	rows, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rows == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// Delete a user by ID
func (r *userRepository) DeleteUser(id string) error {
	res, err := r.db.Exec(`DELETE FROM users WHERE id = $1`, id)
	if err != nil {
		return err
	}
	rows, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rows == 0 {
		return sql.ErrNoRows
	}
	return nil
}